baseURL = "https://minskio.co.uk"
languageCode = "en-gb"
title = "Minskio"
theme = "Brine"
disableFastRender=true

[permalinks]
	posts = "/:title/"

[markup.goldmark.renderer]
	unsafe = true

[params]
	author = "Peter"
	description = "The 'No-Pictures' Blog"

[taxonomies]
	tag = "tags"
	category = "categories"
	recipe = "recipe"
	dream = "dream"
	language = "language"
	memoir = "memoir"

[outputs]
	home = ["HTML", "RSS", "JSON"]
