
name = "Brine"
license = "MIT"
licenselink = "https://github.com/breadcat/blog.minskio.co.uk/blob/master/themes/Brine/LICENSE"
description = "A simple and minimal theme for blogs"
homepage = "https://minskio.co.uk/"
tags = ["blog", "minimal", "responsive"]
features = ["blog", "lightweight", "minimalist", "simple code"]
min_version = "0.41.0"

[author]
  name = "Breadcat"
  homepage = "https://minskio.co.uk/"
